### ISSUE TITLE
Drag'n'drop area non-responsive

### ISSUE THREAD

**Issue by TimonTerBraak** [windelbouwman/lognplot#2]
On Fedora 31 with python3 (3.7.5) and python3-qt5 (5.13.1) the drop area is not working. The signals in the list get nicely updated, but I cannot plot them.

**Comment by windelbouwman** [comment]
What can I say, this sucks! Do you see the drag indicator? This reminds me to make a video on usage. Do you have the four panels on the right? You should be able to drop signals onto the empty panels.

**Comment by TimonTerBraak** [comment]
Yepp, I think the concept was clear. It it similar to the interface of PlotJuggler, right? The drop indicator (+) is nicely appearing when hovering over the area, but nothing happens upon release.

**Comment by windelbouwman** [comment]
Does the signal contain any points?

Otherwise, you would have to put some print statements in this file, where the drop should happen: https://github.com/windelbouwman/lognplot/blob/master/python/lognplot/qt/widgets/dashboard.py

**Comment by windelbouwman** [comment]
> Yepp, I think the concept was clear. It it similar to the interface of PlotJuggler, right? The drop indicator (+) is nicely appearing when hovering over the area, but nothing happens upon release.

Yes, concept is similar, drag signals from the left panel to the right. You could even select multiple signals at the same time.

**Comment by TimonTerBraak** [comment]
Tried to resolve this, but so far no luck. The dragEnterEvent is called and the proposed action is accepted. However, no other drag'n'drop related event is invoked. I also tried with playing around with the mime types (https://stackoverflow.com/questions/42838419/python-pyqt5-qlistwidget-doesnt-accept-drops), but without any luck.
You may find multiple issue regarding drag'n'drop with QWidgets. Is a QFrame a good candidate, or should we pick another widget more suitable for drag'n'drop?

**Comment by windelbouwman** [comment]
QFrame derives from QWidget, so it should be pretty basic, except that is has an extra frame around it.

It might also be caused by the custom mime type, you could try changing the mime type to "text/plain", this is a commonly accepted mime type, and since drag and drop is an OS function, it might be a security thing.

I checked my version info, python 3.8.0 and Qt 5.13.2.

**Comment by TimonTerBraak** [comment]
My last observation is that the problem only occur with Gnome running on Wayland. Running on Xorg seems working fine. Curious, but together with my code review it seems that lognplot is not to blame.

**Comment by windelbouwman** [comment]
That's great news for lognplot! Is there a workaround to make it work? I still suspect the custom mime datatype.

**Comment by TimonTerBraak** [comment]
Found a bug report trail mentioning this issue here:
https://ask.fedoraproject.org/t/qt5-drag-and-drop-problem/4486
https://gitlab.gnome.org/GNOME/mutter/issues/965
https://bugreports.qt.io/browse/QTBUG-80303

The workaround is:
$ QT_QPA_PLATFORM=xcb python -m lognplot
